modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/BrewingCoder/BrewTools/issues" #optional
[[mods]] #mandatory
modId="brewtools" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Brewer's Blocks and Tools" #mandatory
credits="Thanks for all those who have come before..." #optional
authors="BrewingCoder aka BrewDrinkCode" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Night Vision Goggles (Curios compat)
Golden Lasso - Capture friendly mobs
Deco blocks: Abyssal and Quarried similar to old railcraft style blocks
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.brewtools]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.brewtools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.brewtools]]
    modId="curios"
    mandatory=true
    versionRange="[1.18.2-5,)"
    ordering="NONE"
    side="BOTH"