
modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/BrewingCoder/BrewTools/issues"
[[mods]] #mandatory
modId="brewtools" #mandatory
version="${file.jarVersion}" #mandatory
displayName="BrewTools" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://github.com/BrewingCoder/BrewTools"
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="https://media.forgecdn.net/avatars/499/803/637817461302487666.png" #optional
# A text field displayed in the mod UI
credits="All those that have come before. Some textures derived from early Invictus resource packs released under CC3 license.  Ideas on tools from the godly rwtema's Extra Utilities" #optional
# A text field displayed in the mod UI
authors="BrewingCoder (a.k.a. Brewer, BrewDrinkCode)" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Tools from various mods that are dormant:
     * Golden Lasso
     * Redstone Clock
     * Night Vision Goggles
     * Flat, Peaceful Mining Dimension
     * Abyssal and Quarried Stone
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.brewtools]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"

